### PR TITLE
Add filter box to filter databases and tables

### PR DESCRIPTION
**Pull request by maxcnunes**

### CODE REVIEW

**Comment by krolow** [comment]
it wouldn't be better if only update the list instead of have to handle visibility=true/false ?

i mean return a new list without the things that does not fit the search... so we do not need to handle this loadAll and add the if statement to display block/none

**Comment by maxcnunes** [comment]
Initially I implemented such as you said. But I realised once you have changed the state filtering the list you would not have the initial state with all items anymore. This was the only way I find out filtering the list without lose the whole list. Do you have any idea how better implement it?

**Comment by maxcnunes** [comment]
Can I merge it?

**Comment by krolow** [comment]
yes, go for it :+1:

**Pull request merged**
